// <auto-generated />
using System;
using Charts.Api.Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Charts.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014074022_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Charts.Api.Application.Models.ChartReqTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("entity");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("OriginalFromMs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_from_ms");

                    b.Property<DateTime?>("OriginalToMs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_to_ms");

                    b.Property<string>("Params")
                        .HasColumnType("jsonb")
                        .HasColumnName("params");

                    b.Property<string>("SelectedFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_fields");

                    b.Property<string>("Sql")
                        .HasColumnType("text")
                        .HasColumnName("sql");

                    b.Property<string>("TimeField")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("time_field");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Where")
                        .HasColumnType("jsonb")
                        .HasColumnName("where");

                    b.HasKey("Id")
                        .HasName("pk_chart_req_templates");

                    b.HasIndex("DatabaseId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_chart_template_dbid_name");

                    b.HasIndex("DatabaseId", "Entity", "TimeField")
                        .HasDatabaseName("ix_chart_template_dbid_entity_time");

                    b.ToTable("chart_req_templates", (string)null);
                });

            modelBuilder.Entity("Charts.Api.Application.Models.Database", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DatabaseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("database_status");

                    b.Property<string>("DatabaseVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_version");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Entities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("entities");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastConnectivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connectivity_at");

                    b.Property<string>("LastConnectivityError")
                        .HasColumnType("text")
                        .HasColumnName("last_connectivity_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_databases");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_databases_name");

                    b.ToTable("databases", (string)null);
                });

            modelBuilder.Entity("Charts.Api.Application.Models.ChartReqTemplate", b =>
                {
                    b.HasOne("Charts.Api.Application.Models.Database", "Database")
                        .WithMany("ChartReqTemplates")
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chart_req_templates_databases_database_id");

                    b.Navigation("Database");
                });

            modelBuilder.Entity("Charts.Api.Application.Models.Database", b =>
                {
                    b.Navigation("ChartReqTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
